# Generated by Django 2.1.7 on 2023-05-17 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230517_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 17, 18, 20, 22, 446195)),
        ),
    ]
